import Link from 'next/link'
import { ArrowRight, Code, Trophy, Users, Target } from 'lucide-react'

export default function Home() {
  return (
    <div className="min-h-screen bg-[var(--background)] flex flex-col">
      {/* Hero Section */}
      <section className="flex-1 flex items-center justify-center px-4 py-20">
        <div className="max-w-4xl mx-auto text-center">
          <h1 className="text-5xl md:text-6xl font-bold text-[var(--foreground)] mb-6">
            PlacementDuel
          </h1>
          <p className="text-xl text-[var(--text-muted)] mb-8 max-w-2xl mx-auto">
            Compete with your partner in placement preparation tests. Track your progress, analyze your weaknesses, and improve together.
          </p>
          <div className="flex gap-4 justify-center">
            <Link
              href="/auth/signup"
              className="bg-[var(--accent)] hover:bg-[var(--accent-hover)] text-white font-medium py-3 px-6 rounded-lg transition-colors flex items-center gap-2"
            >
              Get Started
              <ArrowRight className="w-5 h-5" />
            </Link>
            <Link
              href="/auth/login"
              className="bg-[var(--card-bg)] border border-[var(--card-border)] hover:bg-[var(--card-border)] text-[var(--foreground)] font-medium py-3 px-6 rounded-lg transition-colors"
            >
              Sign In
            </Link>
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section className="px-4 py-20 border-t border-[var(--card-border)]">
        <div className="max-w-6xl mx-auto">
          <h2 className="text-3xl font-bold text-[var(--foreground)] text-center mb-12">
            Why PlacementDuel?
          </h2>
          <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-6">
            <div className="bg-[var(--card-bg)] border border-[var(--card-border)] rounded-lg p-6">
              <Users className="w-10 h-10 text-[var(--accent)] mb-4" />
              <h3 className="text-lg font-semibold text-[var(--foreground)] mb-2">Partner Up</h3>
              <p className="text-[var(--text-muted)]">Link with a study partner and compete head-to-head in weekly tests.</p>
            </div>
            <div className="bg-[var(--card-bg)] border border-[var(--card-border)] rounded-lg p-6">
              <Code className="w-10 h-10 text-[var(--accent)] mb-4" />
              <h3 className="text-lg font-semibold text-[var(--foreground)] mb-2">AI-Generated Tests</h3>
              <p className="text-[var(--text-muted)]">Tests generated by Google Gemini based on your weekly study topics.</p>
            </div>
            <div className="bg-[var(--card-bg)] border border-[var(--card-border)] rounded-lg p-6">
              <Target className="w-10 h-10 text-[var(--accent)] mb-4" />
              <h3 className="text-lg font-semibold text-[var(--foreground)] mb-2">Smart Evaluation</h3>
              <p className="text-[var(--text-muted)]">AI-powered feedback and scoring using Groq's Llama model.</p>
            </div>
            <div className="bg-[var(--card-bg)] border border-[var(--card-border)] rounded-lg p-6">
              <Trophy className="w-10 h-10 text-[var(--accent)] mb-4" />
              <h3 className="text-lg font-semibold text-[var(--foreground)] mb-2">Track Progress</h3>
              <p className="text-[var(--text-muted)]">Analytics dashboard with performance trends and weak zone analysis.</p>
            </div>
          </div>
        </div>
      </section>
    </div>
  )
}
